name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest - TODO: Fix sharp on Windows
        node: [16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # Checkout repositoroy
      - name: checkout
        uses: actions/checkout@master

      # Cache node_modules
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      # Instal deps
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      # Run linting
      - name: Lint
        run: yarn lint

      # Run tests
      - name: Run tests
        run: yarn test

      # Build Docus package
      - name: Build
        run: yarn build

      # Code coverage
      # - name: Coverage
      #   uses: codecov/codecov-action@v1
